DocumentRoot /var/www/html/repository_jte
ServerName repository.teknikelektro.net
Alias /uploads /var/www/html/repository_jte/uploads
<Directory /var/www/html/repository_jte>
    AllowOverride All
    Require all granted
</Directory>
